// <auto-generated />
namespace LibraryAppDIT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class addNewFieldsToRegisterUserPage6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addNewFieldsToRegisterUserPage6));
        
        string IMigrationMetadata.Id
        {
            get { return "201712031915484_addNewFieldsToRegisterUserPage6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
